api:
  base_url: "http://localhost:8000"
  version: "v1"
  timeout: 30
  
annotation:
  batch_size: 100
  max_retries: 3
  
storage:
  type: "local"
  path: "data/annotations"
  
rewards:
  enabled: true
  calculation_method: "linear"

