api:
  base_url: "https://api.scaile.com"
  version: "v1"
  timeout: 60
  
annotation:
  batch_size: 200
  max_retries: 5
  
storage:
  type: "s3"
  path: "annotations"
  
rewards:
  enabled: true
  calculation_method: "exponential"